### ISSUE TITLE
Doesn't show D2C messages which match a route

### ISSUE THREAD

**Issue by lordbah** [Microsoft/vscode-azure-iot-toolkit#180]
I thought Start Monitoring D2C Message wasn't working since I knew my device was sending messages, and I could see they were being seen by a stream analytics job which listens to the hub, but the extension wasn't printing anything. It wasn't until I disabled the route that the extension showed me the messages. Is there a way to make it work for all D2C messages rather than only unmatched/unrouted ones?

**Comment by formulahendry** [comment]
Hi @lordbah  , could you share how you config the 'Routes' and the 'Endpoints'? If your Endpoint is not Built-in endpoint 'events' (e.g. Azure Storage Container, Event Hubs), the D2C message would not be sent to IoT Hub. Since `Start Monitoring D2C Message` is to monitor the D2C message arrived in IoT Hub.
![image](https://user-images.githubusercontent.com/1050213/46846956-8de40980-ce14-11e8-8de0-8603008b199b.png)

**Comment by lordbah** [comment]
The route is to an endpoint named 'checkin' which is shown under 'Custom endpoints' as an Event Hub.

Is it possible, perhaps through a different tool, to see everything coming IN to the IoT Hub, without disabling routes?

**Comment by formulahendry** [comment]
Hi @lordbah , you could try using https://marketplace.visualstudio.com/items?itemName=Summer.azure-event-hub-explorer to monitor the message coming to your custom Event Hub

**Comment by formulahendry** [comment]
Alternatively, you could add an extra route for monitoring purpose, per answer of https://stackoverflow.com/questions/52810051/read-azure-iot-hub-messages-from-custom-endpoints/52810854#comment92539308_52810051

**Comment by lordbah** [comment]
Thanks.
