### ISSUE TITLE
[C2DMessageMonitor]the status is null after send C2D message to Device

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-toolkit#237]
repro on toolkit 2.1.0-rc

[C2DMessageMonitor] Start monitoring C2D message for [iotdevice]...
[C2DMessage] Sending message to [iotdevice] ...
[C2DMessage] [Success] Message sent to [iotdevice]
[C2DMessageMonitor] Message Received: send c2d message
[C2DMessageMonitor] Status: 

the status is null,  but expect is MessageCompleted.

**Comment by formulahendry** [comment]
This issue is introduced by the webpack which will uglify js for code minimization, and the ‘constructor.name’ used by the message status will be lost during the minimization: https://github.com/Microsoft/vscode-azure-iot-toolkit/blob/c413287a49a1d54e802fc649eb2a56a147758f18/src/iotHubC2DMessageExplorer.ts#L106

So the quick turnaround is to disable the code minimization. Please help test with the latest vsix: https://github.com/Microsoft/vscode-azure-iot-toolkit/releases/download/v2.1.0-rc2/azure-iot-toolkit-2.1.0-rc2.vsix
