### ISSUE TITLE
Dummy JSON tooltip format issue

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode-azure-iot-toolkit#366]
![image](https://user-images.githubusercontent.com/1050213/63487891-820aae80-c4df-11e9-901c-12660e001dce.png)

**Comment by jxtxzzw** [comment]
Already fixed in commit `e588877308d9c22e0d368b56bf279ffedb2da95a`, which I commited after we generated the `vsix`.

This is beacuse In the content slot, content should begin from the left, otherwise unexpected space will be regarded as part of content.

![image](https://user-images.githubusercontent.com/10862845/63498054-b38f7400-c4f7-11e9-8eef-3bfad9d3a217.png)
