### ISSUE TITLE
JSON message should not be stringified

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode-azure-iot-toolkit#367]
![image](https://user-images.githubusercontent.com/1050213/63488092-4d4b2700-c4e0-11e9-9283-bfc34fcc059e.png)

**Comment by jxtxzzw** [comment]
Fixed, and here is the update:

1. User must follow the standard JSON format, otherwise the `JSON.parse()` will fail. If `JSON.parse()` can successfully parse the input, then the message will be sent in JSON Object, and if it fails to parse the input, it will just keep what user inputs as the message(including the `\n`, `\"`, etc.).
```
{
"a": "hello",
"b": [1, 2, 3]
}
```
is valid, and the  result is:
![image](https://user-images.githubusercontent.com/10862845/63499021-99569580-c4f9-11e9-9431-cc5f412c367d.png)

```
{
a: 'hello',
b: [1, 2, 3,],
c: "hello again",
}
```
is invalid, and the result is:
![image](https://user-images.githubusercontent.com/10862845/63499142-d458c900-c4f9-11e9-98ad-cace30bb89ac.png)

> In the above sample, there are 3 mistakes: Properties is not enclosed in double quotation marks; Value is enclosed in single quotation marks; Trailing commas after array element(3,]) and after the last line("hello again",) 

2. In both Plain Text and Dummy JSON, the above rule is valid.

3. The issue is caused by a trailing comma in the Dummy Json Template, which makes `JSON.parse()` take it as an invalid input, and sends it with `\n` and `\"`. 

4. Dummy JSON can parse the template even when there is a trailing comma, so the random result was generated as is depicted in your picture,
