### ISSUE TITLE
[P2] the preview section of Dummy JSON should be more like a read-only view

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode-azure-iot-toolkit#368]
Cuuretly, when I hover on it, the border will be highlighted
![image](https://user-images.githubusercontent.com/1050213/63488746-a87e1900-c4e2-11e9-8cbc-e8ab27b2e709.png)

**Comment by jxtxzzw** [comment]
Fixed by adding a mask over the text area, and if user moves his/her mouse onto the text area, the cursor will be shown in `not-allowed` style. And now, when hovering on disabled/readonly area, the border will not be highlightened.

![image](https://user-images.githubusercontent.com/10862845/63501698-af1a8980-c4fe-11e9-83c1-548aee4cb2a5.png)

![image](https://user-images.githubusercontent.com/10862845/63501718-bcd00f00-c4fe-11e9-8e8e-ffaea4017b39.png)
